### ISSUE TITLE
Allow configuration of pipenv virtualenv location

### ISSUE THREAD

**Issue by vpavlin** [thoth-station/jupyter-nbrequirements#10]
**Is your feature request related to a problem? Please describe.**
In most JupyterHub environments running on Kubernetes a persistent volume would be mounted to a container running Jupyter server. At the same time in most cases this will not cover whole `/home/${USER}/` directory so whatever gets installed with `pipenv` will end up being lost when a container restarts which leads to longer start up times and more network traffic.

**Describe the solution you'd like**
I'd like to be able to configure a destination path prefix for pipenv installation so that we can place that on the persistent volume and thus have the installed dependencies persist across container restarts.

**Describe alternatives you've considered**
The only alternative is to install dependencies on each container restarts which is current state for missing dependencies in our Open Data Hub Jupyter images. It is find if 1 or 2 deps are missing but if we need to install whole environment every time, that would be a pain.

**Comment by CermakM** [comment]
Please, try to set the `WORKON_HOME` env variable and see if it solves your issues.

```python
%env WORKON_HOME=<PIPENV_LOCATION>
```

Cheers,
M
