### ISSUE TITLE
[RFE] Identify installed packages once the notebook is run.

### ISSUE THREAD

**Issue by pacospace** [thoth-station/jupyter-nbrequirements#101]
**Describe the solution you'd like**

As `Data Scientist` I love this project :smiley: and when I run a notebook in an environment I would like to see immediately my current software stack visualized in the nb requirements UI.

**Comment by CermakM** [comment]
Hello @pacospace 

Could you please be more specific whether these packages you want to see in the UI should be from your POV all packages installed within the environment, packages that the notebook requires or packages that the kernel uses?

In the next release, it will be possible to automatically populate the requirements with detected packages from the notebook. Would that satisfy your needs? :stuck_out_tongue: 

Cheers,
M

**Comment by pacospace** [comment]
> Hello @pacospace
> 
> Could you please be more specific whether these packages you want to see in the UI should be from your POV all packages installed within the environment, packages that the notebook requires or packages that the kernel uses?
> 
> In the next release, it will be possible to automatically populate the requirements with detected packages from the notebook. Would that satisfy your needs? 
> 
> Cheers,
> M

That is awesome. I think that is the main one to have. Thank you very much @CermakM !!
