### ISSUE TITLE
Have option to select the resolution engine

### ISSUE THREAD

**Issue by pacospace** [thoth-station/jupyter-nbrequirements#275]
As Data Scientist,

I want to install my dependencies from my notebook but I want to guarantee reproducibility, therefore I want to have a pinned down software stack created.

Currently jupyter-nbrequirement can handle pipenv | thoth resolution engines and use 'micropipenv' to install dependencies.
User should have option to select resolution engine. (default to thoth?)

- [ ] Add extra options in jupyter-nbrequirement extension that allow for selection of resolution engine

**Comment by goern** [comment]
@pacospace could you turn this into a user story with acceptance criteria?
