### ISSUE TITLE
Add more maintainers to PyPI

### ISSUE THREAD

**Issue by pacospace** [thoth-station/jupyter-nbrequirements#281]
Hey @CermakM, 

hope you are good!! We would like to create new releases for jupyter-nbrequirements [1], could you please add more maintainers on pypi from the team, including Sesheta :robot: ?

Thank you very much!!

References:

- [1] https://pypi.org/project/jupyter-nbrequirements/

**Comment by CermakM** [comment]
Heya, sure thing!

I've added both you and sesheta as maintainers. You should receive an invite shortly.

Take care!
M

**Comment by pacospace** [comment]
> Heya, sure thing!
> 
> I've added both you and sesheta as maintainers. You should receive an invite shortly.
> 
> Take care!
> M

Thanks a lot @CermakM!! I will close the issue!!
