### ISSUE TITLE
[TASK] Official Pypi package for jupyter-nbrequirements points to personal github as homepage instead of here

### ISSUE THREAD

**Issue by akchinSTC** [thoth-station/jupyter-nbrequirements#302]
**User story**
[Small nit]
`Homepage` link in pypi package is directed to a fork instead of this github page.

**Additional context**

**Acceptance Criteria**
- [ ] At least once acceptance criteria should be present

**Linked epics / issues**

**Comment by pacospace** [comment]
Thanks @akchinSTC for opening this issue, we are not prioritizing this extension at the moment. Actually, it has been changed in a previous PR (https://github.com/thoth-station/jupyter-nbrequirements/pull/286): https://github.com/thoth-station/jupyter-nbrequirements/blob/cf97e73fe01d7292e0e20e005bb61946aa2abf82/jupyter_nbrequirements/__about__.py#L16 but we need to still release a new version, didn't find time to have a look at this extension. It was developed by one of our ex team member.

Anyway, we are currently actively focused mainly on the jupyterlab extension for dependency management [1]

- [1] https://github.com/thoth-station/jupyterlab-requirements
